#!/command/with-contenv bash
# shellcheck shell=bash

# This cont-init will only be applied if ACMESH_DAEMON is set to "1" which implies
# running the acme.sh renewal daemon. This script is responsible for setting up
# logging prerequisites.

set -eu

if [ -v ACMESH_DAEMON ] && [[ $ACMESH_DAEMON == "1" ]]; then

    echo "** Setting up logging for daemon"

    if [[ $EUID -ne 0 ]]; then
        echo "** Docker container is not started with root user. This is not supported, but will continue."
    fi

    if ! [ -v S6_LOGGING_SCRIPT ]; then
        printf "n30 s10000000 S15000000 T !'gzip -nq9'" >/var/run/s6/container_environment/S6_LOGGING_SCRIPT
    fi

    mkdir -p "$LE_LOG_DIR"
    chown -R "$PUID:$PGID" "$LE_LOG_DIR"

    mkdir -p "$LE_LOG_DIR/acmesh-renewal"
    chown "$PUID:$PGID" "$LE_LOG_DIR/acmesh-renewal"

    mkdir -p "$LE_LOG_DIR/acmesh-renewal"
    chown nobody:nogroup "$LE_LOG_DIR/acmesh-renewal"
    chmod 02755 "$LE_LOG_DIR/acmesh-renewal"


    exec logutil-service "$LE_LOG_DIR/acmesh-renewal"
else
    while true;
    do
        sleep 100
    done
fi