#!/command/with-contenv bash
# shellcheck shell=bash

if [ -v ACMESH_DAEMON ] && [[ $ACMESH_DAEMON == "1" ]]; then
    if [[ $EUID -ne 0 ]]; then
        echo "** Docker container is not started with root user. This is not supported, but will continue."
    fi
    exec 2>&1 s6-setuidgid "$PUID":"$PGID" /usr/local/bin/acmesh-renewal.sh

else
    printf 'acme.sh renewal daemon is ready!\n' >&3
    while true;
    do
        sleep 100
    done
fi