#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# This service script sets up logging service to capture stdin logs

echo "** Launching logger service! Any output from acmesh-renewal service will now be redirected to $LE_LOG_DIR"

S6_LOGGING_SCRIPT_ARGS=()
for arg in $S6_LOGGING_SCRIPT ; do
    S6_LOGGING_SCRIPT_ARGS+=(-a "$arg")
done

exec s6-setuidgid "$PUID":"$PGID" s6-log -bp -- "${S6_LOGGING_SCRIPT_ARGS[@]}" "$LE_LOG_DIR"

