#!/command/with-contenv bash
# shellcheck shell=bash

set -eu

# Wait on the log service to be ready
s6-svwait -t 5000 -U /var/run/s6/services/acmesh-renewal/log

exec 2>&1 s6-setuidgid "$PUID":"$PGID" acmesh-renewal.sh
